Menu_bar:

<Menu_bar>:
    orientation : "vertical"
    Label:
        text: "Optimized-Suggested Smart Parking System"
        font_size : "63dp"
        font_name: "fonts/KaushanScript-Regular.otf"
        color : 1,1,0.5,1,
        size_hint: 1,0.2
    MainFrame:

<MainFrame>:
    orientation: "horizontal"
    Button:
        text: "Enterance Under developement........"
    Button:
        text: "Exit Under Development.............."

